runtime: java17
env: standard

entrypoint: java -Dserver.port=8080 -jar ems-backend-0.0.1-SNAPSHOT.jar

resources:
  cpu: 1
  memory_gb: 1
  disk_size_gb: 10

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 2
  cool_down_period_sec: 60
  cpu_utilization:
    target_utilization: 0.6

readiness_check:
  path: "/"
  check_interval_sec: 5
  timeout_sec: 4
  failure_threshold: 3
  success_threshold: 2
  app_start_timeout_sec: 600

liveness_check:
  path: "/health"
  check_interval_sec: 10
  timeout_sec: 4
  failure_threshold: 5
  success_threshold: 2
  initial_delay_sec: 300










