runtime: java
env: flex
entrypoint: java -jar target/ems-backend-0.0.1-SNAPSHOT.jar

resources:
  cpu: 1
  memory_gb: 1
  disk_size_gb: 10

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 2
