name: Deploy to GCP App Engine

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Move JAR to root directory
        run: |
          cp target/ems-backend-0.0.1-SNAPSHOT.jar .
          echo "Moved JAR to root for deployment"

      - name: Print working directory and list files
        run: |
          pwd
          ls -al

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: Deploy to Google App Engine
        uses: google-github-actions/deploy-appengine@v2
        with:
          deliverables: app.yaml
          project_id: java-backend-460409
          promote: true
          flags: '--quiet'

